version: '3.1'

volumes:
  pg_project:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=sa
      - POSTGRES_DB=gentt
    volumes:
      - pg_project:/var/lib/postgresql/data
      - ".scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
    ports:
      - ${POSTGRES_PORT:-5432}:5432
